=== Функциональные требования

. Пользователь может просматривать каталог товаров (с фильтрацией и сортировкой)
. Пользователь может собрать товары из каталога в корзину (>=1 экземпляра товара)
. Пользователь может оформить заказ товаров из корзины на какой-то адрес
. Система должна проверять допустимость адреса доставки
. Пользователь может выбрать способ оплаты, в т.ч. оплатить он-лайн
. Система должна требовать от неаутентифицированного пользователя идентификатор (номер телефона, логин в мессенджере и т.п.)
. Супервайзер может добавлять, удалять, менять количество экземпляров и редактировать описание товаров

. Администратор может забанить пользователя по использовавшемуся идентификатору

==== Бэклог

. Супервайзер может удалить товар во время заказа пользователем.
Должна быть возможность отмены заказа и уведомления пользователя.
. Аутентифицированный пользователь может указать свои данные в профиле
. Для аутентифицированных пользователей возможны персональные скидки/цены/акции
. Аутентифицированные пользователи могут составлять список "любимых" товаров
. Метрики, аналитика пользовательских действий
