=== Описание концептуальной архитектуры

Система "Сервис заказа и доставки продуктов" предоставляет API для
следующих потребителей: клиент, администратор, супервайзер.
Авторизация всех пользователей к системе производится на основе ролевой
модели. Аутентификация и маршрутизация запросов производятся в слое API Gateway.
Система обращается к внешним системам для обеспечения платежей, валидации
адресов доставки и уведомления пользователей по разным каналам связи.

Система построена в микросервисном стиле для удобства масштабирования
отдельных узлов при росте числа и географии пользователей.

Сервисом, обеспечивающим core-функциональность для пользователя, является
Сервис Заказов. Он отвечает за создание и хранение артефактов заказа. Хранит
данные в реляционной базе данных. Сервис Заказов синхронно получает данные о
наборе продуктов из Сервиса Корзины, обращается к Сервису Проверки Адресов
для валидации введённого клиентом адреса доставки, обращается к Сервису
Платежей для проведения оплаты, публикует сообщения в топик для Сервиса
Уведомлений, публикует сообщения в топик для Сервиса Товаров.

Сервис Корзины обеспечивает для клиента функциональность предварительного
набора продуктов для создания заказа. Хранит данные в кратковременном
хранилище данных с TTL. Сервис Корзины синхронно получает информацию из
Сервиса Товаров.

Сервис Товаров реализует каталог товаров. Наполняется супервайзером и
просматривается клиентом для выбора товаров в корзину. Сервис Товаров хранит
данные в реляционных базах данных, применяя CQRS.

Сервис Проверки Адресов обращается во внешнюю систему проверки адресов для
валидации и очистки адресов и кэширует результаты.

Сервис Платежей обращается во внешнюю систему платежей для безопасной оплаты
он-лайн.

Сервис Уведомлений вычитывает из топиков события и формирует уведомления для
клиентов. Обращается во внешние системы уведомлений для доставки
пользователям сообщений разными способами.

Сервис Управления Пользователями обеспечивает хранение и изменение профилей
клиентов и обеспечивает администраторам функциональность для бана/разбана
пользователей. Хранит данные в реляционной базе данных. Публикует сообщения в
топик для Сервиса Уведомлений.
